image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - apt-get update -y && apt-get install -y python3 python3-pip python3-venv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install awscli
  script:
    - npm install
    - npm run build
    - aws s3 sync ./build s3://oneplustwo.team --delete
    - aws s3 cp s3://oneplustwo.team/index.html s3://oneplustwo.team/index.html --metadata-directive REPLACE --cache-control max-age=0 --content-type "text/html"

  only:
    - main
